### ISSUE TITLE
Self Hosting

### ISSUE THREAD

**Issue by prologic** [microdotblog/issues#160]
Hi,

I'm interesting in trying Micro Blog but I don't see an option to Download the software and install it on my own server. Is this possible? Can I self-host on my own infrastructure?

Kind Regards

James

**Comment by manton** [comment]
Thanks @prologic! It's not possible right now to install all of Micro.blog on your own server. Instead, the approach Micro.blog takes is to build on top of existing blog software. For example, behind the scenes in Micro.blog it is using the Hugo engine as part of publishing your blog hosted on Micro.blog.

If you want to self-host on another server, we recommend just using existing blog software. Lots of people use WordPress, and we have [a guide here on setting it up](https://help.micro.blog/2018/setting-up-wordpress/). You can then connect it to Micro.blog on the Account → "Edit Feeds & Cross-posting" page.

I hope we'll be able to open source more of Micro.blog in the future. And because you're using your own domain name with Micro.blog, you can always move your blog later.
