### ISSUE TITLE
Web form image uploading does not respect orientation attributes

### ISSUE THREAD

**Issue by shindakun** [microdotblog/issues#161]
Issue: Uploading image results in an image that doesn't take into account the EXIF orientation data.

Steps to recreate:

1. Download https://shindakun.micro.blog/uploads/2019/2ac8cb111f.jpg and view it on a computer note it is displayed correctly
2. Upload via the webform
3. View post (for example https://shindakun.micro.blog/2019/12/01/dilophosaurus-preparing-to.html)

**Comment by ghost** [comment]
This problem has been spoken about so much that I was sure there was already an issue. Thanks for posting it. 👍

**Comment by jsonbecker** [comment]
This issue is related to browsers not respecting EXIF orientation data.

The answer [here on Stack Overflow](https://stackoverflow.com/questions/12026441/is-there-a-way-to-tell-browsers-to-honor-the-jpeg-exif-orientation) helped me to diagnose it. Unfortunately, browsers haven't fixed this, so I used `mogrify -auto-orient` from image magick to fix this.

I'm not sure if any server-side image processing happens on Micro.blog, but it seems like adding that may be a path to fixing this, regardless of where the image comes from.

**Comment by sardisson** [comment]
It’s browsers not respecting EXIF Orientation when the image _is shown in a page_; if you click the link in step 1, it will display correctly because it’s just the image.

Inexplicably, Mobile Safari *does* correctly respect EXIF Orientation in images in web pages, but it’s the only browser I’m aware of that does so.

@manton [mentioned the other day](https://micro.blog/manton/7165716#post_div_7165716) that the orientation issue is something that needs to be improved in the web upload.

**Comment by manton** [comment]
I think this is fixed now. Micro.blog should strip out the orientation information when it's uploaded in all cases now, not just from the native apps like it was doing before. Thanks everyone.
