### ISSUE TITLE
HTTPS for Mapped Custom Domains

### ISSUE THREAD

**Issue by jbrayton** [microdotblog/issues#35]
I mapped micro.virtualsanity.com to my microblog. When I visit the microblog at https://micro.virtualsanity.com/ I get a certificate error. It looks like micro.blog uses a certificate for "*.micro.blog" even when accessed by a mapped custom domain.

**Comment by manton** [comment]
@jbrayton I'm considering offering free SSL certs for anyone using a custom domain, via Let's Encrypt. Otherwise you'd have to upload your own SSL cert, which is really too difficult for most people. Hope to make this a priority soon, as well as start redirecting more URLs to HTTPS by default. Thanks!

**Comment by manton** [comment]
We do allow SSL now for custom domains. I have to manually enable it (email help@micro.blog), but it's quick and I can usually do it the same day as receiving the request.
