### ISSUE TITLE
Should micro.blog parse RSS–fed posts for at–mentions?

### ISSUE THREAD

**Issue by cdn** [microdotblog/issues#64]
https://micro.blog/cn receives initial posts from two RSS feeds at https://charlienovemb.re.

So far origin posts with at–mentions have not produced links to profiles in the interface, and presumably no notifications to those mentioned.

**Comment by manton** [comment]
Currently mentions aren't parsed from external RSS feeds, since it's difficult to know what the author intends. And you're right that if the mentions aren't detected and linked, no notifications are sent.

I'm not sure what the right behavior is. Another option is that external sites can send Webmention pings to Micro.blog and it will process them as replies and send notifications to users if necessary. There is room for improvement here, though.

**Comment by manton** [comment]
We recently added better support for @-mentions from RSS or JSON feeds. This help page describes the behavior: http://help.micro.blog/2018/replies-and-mentions/
