### ISSUE TITLE
Using micropub summary property as fallback

### ISSUE THREAD

**Issue by gRegorLove** [microdotblog/issues#92]
If there is no `content` or `photo` in a micropub request, could micro.blog fall back to the `summary` property if it exists?

[indiebookclub](https://indiebookclub.biz) is posting read posts with the following micropub JSON syntax:

```json
{
  "type": ["h-entry"],
  "properties": {
    "summary": ["Want to read: Title by Author, ISBN: ISBN"],
    "read-status": ["to-read"],
    "read-of": [
      {
        "type": ["h-cite"],
        "properties": {
          "name": ["Title"],
          "author": ["Author"],
          "uid": ["ISBN"]
        }
      }
    ]
  }
}
```

A couple people on micro.blog tried it and received a 400 error: `{"error":"invalid_request","error_description":"No content or photo."}`

It appears Known is falling back to the summary property: https://michael.runcieman.com/2018/want-to-read-snow-crash-by-neil-stephenson-isbn-9780553380958

Discovered via: http://www.kimlosey.me/2018/06/09/gregor-morrill-aka.html

**Comment by aaronpk** [comment]
The `summary` property is intended to be used for fallback for when the server doesn't recognize the other properties of the request. Most Micropub servers understand `content` and `photo`, but this is a great example of an interesting content type that is likely not supported by most servers yet. In this case, `summary` is the correct place for this fallback content. The `content` property would be misleading since normally the `content` property contains user-entered text. For example, if the user enters a note about why they wanted to read this, that could be included in the `content` property.

**Comment by manton** [comment]
Thanks for writing this up! Thinking through the indiebookclub use case... Right now it sends `summary`. Simple enough. But what if a feature is added that lets the user enter some text about the book? That would go into `content`, of course. But if content doesn't include both the original summary (what book the person wants to read) _and_ the new text, servers that take the text will lose the previous information about the book.

The example as it exists today:

summary: "Want to read: Book Title"
server displays: "Want to read: Book Title"

But if text is added:

summary: "Want to read: Book Title"
content: "I've heard this book is great!"
server displays: "I've heard this book is great!"

Now the post looks worse because the reader has no idea what book the post is talking about. To "fix" this, maybe add the summary in parenthesis:

summary: "Want to read: Book Title"
content: "I've heard this book is great! (Want to read: Book Title)"
server displays: "I've heard this book is great! (Want to read: Book Title)"

But at that point, why have `summary` at all? Why not just use `content` as the fallback and simplify the whole thing to a single common parameter?

**Comment by aaronpk** [comment]
This is definitely a tricky case, but I would suggest the opposite:

summary: "I've heard this book is great! - Want to read: Book Title"
content: "I've heard this book is great!"
read-of: (h-cite object)

**Comment by gRegorLove** [comment]
I considered adding a notes/comment field and probably will at some point. I like @aaronpk's idea to include it in the summary.

**Comment by manton** [comment]
I don't think this really solves the problem, though. If a server implementation prefers `content` over `summary` (which it should), with this example the context of the book title will be lost unless the server is updated to understand `read-of`.

**Comment by aaronpk** [comment]
Maybe the logic could be "if the request contains *any* unrecognized properties, the server uses the summary property instead"?

**Comment by gRegorLove** [comment]
That sounds good, but would it cause problems in some instances? E.g. if the server understood `photo` but not `location`.

**Comment by manton** [comment]
That example would apply to Micro.blog, since it does understand `photo` but not `location` yet.

Another solution would be for services like indiebookclub to always send the most complete fallback in `content` but also supply additional parameters with the details. For example:

content: "I've heard this book is great! - Want to read: Book Title"
read-comment: "I've heard this book is great!"
read-of: (h-cite object)

What I'm not sure I have a good grasp of yet is whether this is a one-off example that only applies to indiebookclub or if this is relevant to other services. I assume the latter, but it would be good to walk through other examples if people have them.

**Comment by gRegorLove** [comment]
The more I think about it, I wonder if a note/comment about a read post is a separate post, like a [reply](https://indieweb.org/reply) to a read post.

I'm hesitant to add the `read-comment` property currently because I'm not selfdogfooding that property (I've not even manually posted notes/comments in my read posts so far). I ran into problems before ([some notes](https://gregorlove.com/2018/06/now-that-indiebookclub-is-launched/)) by trying to set up the micropub properties first. I now understand better that published examples should come first and inform the micropub request.

**Comment by manton** [comment]
We discussed this at IndieWeb Summit and I added initial support for falling back on `summary`. Thanks!
